### ISSUE TITLE
You do not have the appropriate permissions

### ISSUE THREAD

**Issue by devseevali** [kaakaa/matterpoll-emoji#10]
When I try to execute `/poll 'What do you gys wanna grab for lunch?' :pizza: :sushi: :fried_shrimp: :spaghetti: :apple:` I just get `Command with a trigger of 'poll' returned an empty response` as an error.

I'm using **matterpoll-emoji-v0.0.2-linux-x86_64.tar.gz**. To test, executed `./matterpoll-emoji`.
And the console displays `You do not have the appropriate permissions,` when executing `/poll` in Mattermost.

Content of the config.json:
```json
{
	"host": "http://my-mm-server-address:port",
	"user": {
		"id": "user_name",
		"password": "password"
	}
}
```
The user (user_name) can log in to the Mattermost.

**Comment by kaakaa** [comment]
Thank you for reporting the issue. @devseevali.

The message `You do not have the appropriate permissions` may be from Mattermost.
`matterpoll-emoji` calls the following Mattermost API.
* Login
* CreatePost
* SaveReaction

I suppose that your user (user_name) don't have proper permission for creating a post.
Can that user(user_name) post a message to the channel in which slash command executed?

**Comment by devseevali** [comment]
It's now fixed. The polling user added to the channel.

Thanks @kaakaa!

**Comment by kaakaa** [comment]
Glad to hear it!

However, it is not good that a meaningless message appeared when command failed.
I'll improve message in the future.

Thanks a lot @devseevali.
