### ISSUE TITLE
"Command with trigger of 'poll' returned an empty response" while working

### ISSUE THREAD

**Issue by flexo3001** [kaakaa/matterpoll-emoji#14]
The poll is working as expected but i keep getting the banner/error 

![screen shot 2017-07-11 at 21 02 02](https://user-images.githubusercontent.com/1415596/28086118-2fe98908-667e-11e7-9b12-71daa947b7f0.png)

I deployed the precompiled binary.

**Comment by Hanzei** [comment]
This error is cast by the way matterpoll is sending the response. #9 is related.

**Comment by flexo3001** [comment]
@Hanzei Thank you for the fast answer!

**Comment by Hanzei** [comment]
Fixed with  #37
