### ISSUE TITLE
Matterpoll is returning an empty response to mattermost

### ISSUE THREAD

**Issue by Hanzei** [kaakaa/matterpoll-emoji#2]
When I try to execute `/poll `What do you gys wanna grab for lunch?` :pizza: :sushi: :fried_shrimp: :spaghetti: :apple:` I just get `Command with a trigger of 'poll' returned an empty response` as an error.
The go log shows this error: `2017/03/29 10:25:44 AppErrorFromJson: model.utils.decode_json.app_error, body: 404 page not found`

**Comment by kaakaa** [comment]
Thanks for your feedback!

Mattermost version may be the cause of this issue.
I tested matteropll-emoji on mattermost v3.7.2.

Could you tell me your mattermost version?

**Comment by Hanzei** [comment]
Version: 3.7.0  (3.7.2)
Database: postgres
Webproxy: nginx

**Comment by kaakaa** [comment]
Probably I understood the cause. It's not the difference of versions.

Have you set the url of matterpoll-emoji to `host` in config.json?
Please try setting the url of mattermost (ex. http://localhost:8065) to `host` in config.json.

**Comment by Hanzei** [comment]
I set the url to `"host": "http://mattermost.mydomain.com:62391"`.
Is it necessary to create a user and set the id and password `the config.json`?

**Comment by kaakaa** [comment]
You must write id and password of existing account of mattermost to config.json.
That account posts messages about poll to Mattermost.

You can use your account's id/password. In that case, it does not necessarily have to create a user.

**Comment by Hanzei** [comment]
Set a password and an id in `config.json` but it didnt fix the problem

**Comment by Hanzei** [comment]
I set `host` to the url of my mm server and it worked! Thank you @kaakaa !
