### ISSUE TITLE
Share your work with Mattermost community?

### ISSUE THREAD

**Issue by jasonblais** [kaakaa/matterpoll-emoji#3]
Hi @kaakaa,

Saw your work on "matterpoll" and we'd love to help share it with the Mattermost community. Would you be open to sharing more about your project? https://www.mattermost.org/share-your-mattermost-projects/

We could include the integration as part of our April release announce, timed with the emoji picker and reactions beta release in April.

Wonderful work!

**Comment by kaakaa** [comment]
Wow, it's good to hear!
I'll send the form about `matterpoll-emoji` soon.

Thank you @jasonblais 😄

**Comment by kaakaa** [comment]
`matterpoll-emoji` have been introduced in [Mattermost 3.8 Release Blog](https://about.mattermost.com/mattermost-3-8/#matterpoll).

Thanks jason!!
