### ISSUE TITLE
Level based logging

### ISSUE THREAD

**Issue by hanzei** [kaakaa/matterpoll-emoji#55]
Logging on a level based system allows better developing and debugging. There are a couple of option:

- https://github.com/op/go-logging (Last commit 03/2016)
- https://github.com/cihub/seelog (Last commit 01/2017)
- https://github.com/ccpaging/log4go (Still maintained)
- https://github.com/Sirupsen/logrus (Still maintained)

**Comment by kaakaa** [comment]
We are focusing to develop [Matterpoll](https://github.com/matterpoll/matterpoll) plugin.
Please consider using this plugin.
