### ISSUE TITLE
Localise error messages

### ISSUE THREAD

**Issue by hanzei** [kaakaa/matterpoll-emoji#56]
Since we provide a couple of error messages for the users, we should localise them. [go-i8m](https://github.com/nicksnyder/go-i18n) seams to be the standard.
There are two ways to figure out which localisation we should provide:
- Configure a language via config file
- Use the Mattermost API to access the system config and hope only one language is defined
Both ways seams ok to me, but maybe there is a better way.

**Comment by kaakaa** [comment]
We are focusing to develop [Matterpoll](https://github.com/matterpoll/matterpoll) plugin.
Please consider using this plugin.
