### ISSUE TITLE
Support personal access token

### ISSUE THREAD

**Issue by kaakaa** [kaakaa/matterpoll-emoji#57]
It seems that Mattermost is going to support `personal access token` for authenticating REST API from next version.
[PLT-6763 Implement user access tokens and new roles (server-side) by jwilander · Pull Request #6972 · mattermost/platform](https://github.com/mattermost/platform/pull/6972)
(`user access token` renamed `personal access token` later)

We should support authenticating by `personal access token`  instead of user and password.

**Comment by Hanzei** [comment]
So we have to replace `login()` with another method, haven't we? What is the name of the method? I didn't find one in https://github.com/mattermost/platform/blob/master/model/client4.go

**Comment by kaakaa** [comment]
Sorry for my late reply.

If we use personal access token, we set AuthToken/AuthType directly to `model.Client` instead of using `login()` .
https://github.com/mattermost/mattermost-server/blob/master/model/client4.go#L463

The following code works fine for me.
```
package main

import (
	"log"

	"github.com/mattermost/platform/model"
)

const Token = "dummy_access_token"

func main() {
	c := model.NewAPIv4Client("http://localhost:8065")
	c.AuthToken = Token
	c.AuthType = model.HEADER_BEARER

	u, _ := c.GetMe("")
        log.Printf("%+v", u)
}
```

**Comment by DoktorAerzt** [comment]
I have made a fork to test your solution. At the moment the matterpoll bot is working. I don´t made a Pull Request cause it´s hardcoded to only use the Token and in my version you have no chance to go back to User/Password authentication.

**Comment by kaakaa** [comment]
[Matterpoll](https://github.com/matterpoll/matterpoll) plugin doesn't need any authentication methods.
Please consider using this plugin.
