### ISSUE TITLE
Offer Docker image

### ISSUE THREAD

**Issue by jostyee** [kaakaa/matterpoll-emoji#6]
That'll be much convenient.

**Comment by kaakaa** [comment]
Thanks @jostyee for a good suggestion!
I agree that it is useful to build docker image.

Would you be interesting in submitting a PR about Dockerfile?

**Comment by jostyee** [comment]
I tried but the repo's releases tag versions & archs are really confusing.

**Comment by kaakaa** [comment]
Oh...I mistook the tag number to archives, sorry. I've fixed the version number of the archive names.
And archs follows the description of [this site](https://golang.org/doc/install/source#introduction).
```
amd64 (also known as x86-64)
  A mature implementation.
386 (x86 or x86-32)
  Comparable to the amd64 port.
```

Do you have any other points that confused you?

**Comment by jostyee** [comment]
`uname -m` returns `x86_64` so you can't construct a download url based on the host arch simply pass this param.

**Comment by kaakaa** [comment]
Make sense, that's important.
I've fixed archs and version tag of release archive names.

**Comment by jostyee** [comment]
Sorry for the delay, I've met another issue, this repo doesn't support GitLab OAuth login, which I need to test 'cause we have disabled user/passwd login method.

**Comment by kaakaa** [comment]
Thank you for reporting it! Yes, as you say matterpoll supports only user/passwork as login method.
I made issue #8 and I'll work on this. Please wait for closing #8.

**Comment by kaakaa** [comment]
We are focusing to develop [Matterpoll](https://github.com/matterpoll/matterpoll) plugin.
Please consider using this plugin.
