### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by kaakaa** [kaakaa/matterpoll-emoji#76]
We have a lot of change from releasing v0.2.0, so planning to ship v0.1.0!

## Release Tasks

- [x] Fix travis settings
- [ ] Write release notes / changelog

**Comment by Hanzei** [comment]
PR for the chagelog #84

**Comment by Hanzei** [comment]
See https://github.com/kaakaa/matterpoll-emoji/releases/tag/v0.1.0
