### ISSUE TITLE
Message Buttons

### ISSUE THREAD

**Issue by hanzei** [kaakaa/matterpoll-emoji#87]
Mattermost 4.2 will add interactive messages (https://github.com/mattermost/platform/pull/7274). We should use this new feature and get ride of user credentials.

**Comment by PtrBld** [comment]
Interactive action buttons do not support emojis atm.

**Comment by kaakaa** [comment]
We implement this feature in [Matterpoll](https://github.com/matterpoll/matterpoll) plugin.
Please consider using this plugin.
