### ISSUE TITLE
Use token instead of user information

### ISSUE THREAD

**Issue by axiix** [kaakaa/matterpoll-emoji#9]
A slash integration gets a token and with that one can authenticate against mattermost.
This seems to be a nicer method as then you do not need another user to post the message in the channel. Also you can use the slash command in any channel :)

**Comment by kaakaa** [comment]
Hi @axiix!
Thank you for comments and sorry for my late replying.

I don't know how to authenticate users by slash command's token.
I tried to authenticate user by using the token, but I received the error message `Invalid or expired session, please login again.`.

```
package main

import (
	"log"

	"github.com/mattermost/platform/model"
)

func main() {
	c := model.NewClient("http://localhost:8065")
	c.SetOAuthToken("SLASH_COMMAND_TOKEN")
	c.SetTeamId("TEAM_ID")
	r, err := c.GetMe("")
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("%f", r)
}
```

---

I think that slash command's token is for identifying that a request is sent by slash command, is not for authenticating users.

[Set Up a Custom Command](https://docs.mattermost.com/developer/slash-commands.html#set-up-a-custom-command)
> 4. Your new slash command will be displayed with a Token that your external application should use to verify the request came from Lattermost.

If you know more about this, please let me know. 
Thanks.

**Comment by Hanzei** [comment]
The giphy integration for mattermost handles there requests with tokes. You might want to take a look at there code. See https://github.com/numberly/mattermost-integration-giphy

**Comment by kaakaa** [comment]
Thanks @Hanzei!!

I tried reading codes of `mattermost-integration-giphy`.
It seems that they use the token only to verify the validity of the request, and they do not seem to use it for user authentication...
https://github.com/numberly/mattermost-integration-giphy/blob/master/mattermost_giphy/app.py#L48

**Comment by Hanzei** [comment]
@kaakaa It seems you are right. But if you look at there installation guide you wont find any information about a user account (https://github.com/numberly/mattermost-integration-giphy/blob/master/LINUX.md) I set up `mattermost-integration-giphy` for my mattermost instance and didnt needed a account.
Is it possible that there is no authentication at all?

**Comment by kaakaa** [comment]
As you say if just posting a message, it doesn't need user information and just reply json data including `text` field to Mattermost.
[Slash Commands — Mattermost 3\.10 documentation](https://docs.mattermost.com/developer/slash-commands.html#creating-integrations-with-commands)

But in that way it cannot add any Reactions.
We can add Reactions for messages through API or Web UI and cannnot reaction for messages from the response for slash command.

Now, `matterpoll-emoji` adds Reacitons through [Mattermost API](https://api.mattermost.com/#tag/posts%2Fpaths%2F~1teams~1%7Bteam_id%7D~1channels~1%7Bchannel_id%7D~1posts~1%7Bpost_id%7D~1reactions~1save%2Fpost) using authenticated client. 
[matterpoll\-emoji/poll\_func\.go at master · kaakaa/matterpoll\-emoji](https://github.com/kaakaa/matterpoll-emoji/blob/master/poll/poll_func.go#L70)

So `matterpoll-emoji` needs user information.

**Comment by Hanzei** [comment]
@kaakaa You are right. We can`t add reactions without user informations.
